# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Weather App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
# Name of job is build-application
  build-application:

    runs-on: ubuntu-latest

    steps:
    # clones weatherapp repo to $GITHUB_WORKSPACE which is the working directory of the runner
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Setup a dotnet cli environment with dotnet version 8 where you can run the dotnet restore and build command below
    - name: Setup .NET Environment 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

      # Download any missing packages
    - name: Restore dependencies
      run: dotnet restore

      # Build the application
      
    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ${{env.GITHUB_WORKSPACE}}/weatherapp-release
      
      # Log env 
    - name: Execute the following commands
      run: |
          echo "HOME is : ${HOME}"
          echo "GITHUB_WORKFLOW is : ${GITHUB_WORKFLOW}"
          echo "GITHUB_REPOSITORY is: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME is : ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE path : ${GITHUB_WORKSPACE}"
