name: Events Acvities

on:
    pull_request:
        types: 
            - opened
        branches:
            - feature
    push:
        branches:
            - master
            - RR*
        paths-ignore:
            - '.github/workflows/event.yml'
jobs: 
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Output events 
              run: |
                    echo "Pull Request Title: ${{ github.event.pull_request.title }}"
                    echo "Pull Request Body: ${{ github.event.pull_request.body }}"
                    echo "Pull Request Number: ${{ github.event.pull_request.number }}"
                    echo "Pull Request State: ${{ github.event.pull_request.state }}"